bundler_args: --without development
script: "bundle exec rake db:migrate test"

rvm:
  - 1.8.7
  - 1.9.3
  - ree

# Not testing on JRuby until the following DJ bug is fixed:
# https://github.com/collectiveidea/delayed_job/issues/328
#  - jruby
# Not until the RDF gem is upgraded, else we'll take up
# years of build time on the poor Travis servers.
#  - rbx

before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "cp config/app_config.yml.travis config/app_config.yml"
  - "mkdir downloads"
  - "mysql -e 'create database rletters_test;'"
