language: ruby
cache: bundler
rvm: 2.3.0
sudo: false

# Set the display value and the CodeClimate repository token
env:
  global:
    - DISPLAY=":99.0"
    - DATABASE_URL="postgres:///rletters_test?username=postgres&pool=20&encoding=unicode"
    - secure: Lv1neEs259UnYFTpbBOja4qhbdDnDCryGiZ8ycLkBGlc7PioiSiVqCo1Py+pJrpYenA3xrguv/Z5hdNjJ3fm4dl8GDrV9kgjtNe8E388kitISpimAi5QuwvxfJS8YiRPKm9VSfs3laMlSVXjhMdlAW1PPcrcElddv+r+jMpJ9uM=

# Enable the latest PostgreSQL
addons:
  postgresql: 9.4

bundler_args: "--without production development --jobs 3 --retry 3"
before_script:
  - sh -e /etc/init.d/xvfb start
  - ln -s .env.example .env
  - git clone --depth=1 https://github.com/rletters/solr-example.git vendor/solr
  - 'pushd vendor/solr && ./start && popd'
  - bundle exec rake RAILS_ENV=test db:setup assets:precompile

script: bundle exec rspec
