bundler_args: --without production development
script: "bundle exec rspec"

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby-18mode
  - jruby-19mode

# Not until the RDF gem is upgraded, else we'll take up
# years of build time on the poor Travis servers.
#  - rbx-18mode
#  - rbx-19mode

before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "cp config/app_config.yml.travis config/app_config.yml"
  - "mkdir downloads"
  - "mysql -e 'create database rletters_test;'"
  - "bundle exec rake db:test:load db:test:prepare"
