sudo: required
dist: trusty

language: ruby
rvm: 2.5.0

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

env:
  global:
    - TMPDIR=$TRAVIS_BUILD_DIR/tmp
    - DISPLAY=":99.0"
    - RAILS_ENV=test
    - DATABASE_URL="postgres:///rletters_test?username=postgres&pool=20&encoding=unicode"
    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    - secure: umc1IysRHrVN9iN6AtT0sp6C+9ZaZYlXHRpCE7Qk2nKMPfOwrARBN/q16VpI/L8LTj6IbTGRGQ1wCOaGduJ661E5UenSTXNDoD8BzUofTRn3nwW4wO50DMhKppTEW9Nk44WkTGOtTC2Zm+Q8X0CGmQQJJkIBmIiOeNAD6CnfmgQ=

addons:
  postgresql: 9.6
  chrome: stable
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y -qq libsdl1.2-dev libsdl-ttf2.0-dev
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - jdk_switcher home oraclejdk9
  - git clone --depth=1 https://github.com/rletters/solr-example.git vendor/solr
  - bundle install --without production development tools --jobs 3 --retry 3
  - yarn

before_script:
  - sh -e /etc/init.d/xvfb start
  - ln -s .env.example .env
  - pushd vendor/solr && ./start && popd
  - bin/rails db:setup
  - ./cc-test-reporter before-build

script:
  - bin/rails test
  - bin/rails test:system

after_script:
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
