bundler_args: --without production development
script: "bundle exec rspec"

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree

# Not until the following pull request is taken up by the
# latex-decode gem, otherwise it uses a binary C
# extension which won't load on Travis:
# https://github.com/inukshuk/latex-decode/pull/3
#  - jruby

# Not until the RDF gem is upgraded, else we'll take up
# years of build time on the poor Travis servers.
#  - rbx

before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "cp config/app_config.yml.travis config/app_config.yml"
  - "mkdir downloads"
  - "mysql -e 'create database rletters_test;'"
  - "bundle exec rake db:test:load db:test:prepare"
