language: ruby

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.mri
    - rvm: 2.0
      gemfile: gemfiles/Gemfile.mri
    - rvm: jruby-19mode
      gemfile: Gemfile
      env: JRUBY_OPTS="-Xcompile.invokedynamic=false"

before_install: gem install --pre bundler
bundler_args: --without production development

before_script: cp config/database.yml.travis config/database.yml
script: bundle exec rspec
