language: ruby
rvm:
  - 1.9.3
  - 2.0

before_install: gem install --pre bundler
bundler_args: --without production development

before_script: cp config/database.yml.travis config/database.yml
script: bundle exec rspec
