language: ruby
rvm:
  - 1.9.3

branches:
  only:
    - master

bundler_args: --without production development

before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "mkdir downloads"
  - "mkdir public/static_assets"
  - "script/solr_start $PWD"

script:
  - "bundle exec rake spec --trace"

after_script:
  - "script/solr_stop $PWD"
