language: ruby
cache: bundler
rvm: 2.2.0
sudo: false

env:
  matrix:
    - TASK='bin/rspec'
    - TASK='bin/cucumber --profile first_try || bin/cucumber --profile second_try'
  global:
    secure: Lv1neEs259UnYFTpbBOja4qhbdDnDCryGiZ8ycLkBGlc7PioiSiVqCo1Py+pJrpYenA3xrguv/Z5hdNjJ3fm4dl8GDrV9kgjtNe8E388kitISpimAi5QuwvxfJS8YiRPKm9VSfs3laMlSVXjhMdlAW1PPcrcElddv+r+jMpJ9uM=

bundler_args: "--without production development --jobs 3 --retry 3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - git clone --depth=1 https://github.com/rletters/solr-example.git vendor/solr
  - 'pushd vendor/solr && ./start && popd'
  - bin/rake db:create db:schema:load

script: sh -c "$TASK"

after_script: 'pushd vendor/solr && ./stop && popd'
