language: ruby
rvm:
  - 1.9.3

branches:
  only:
    - master

bundler_args: --without production development

before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "mkdir downloads"
  - "bundle exec rake db:migrate db:test:load db:seed_fu"

script:
  - "bundle exec rake spec"
