language: ruby
cache: bundler
rvm: 2.2.3
sudo: false

# Set the display value and the CodeClimate repository token
env:
  global:
    - DISPLAY=":99.0"
    - secure: Lv1neEs259UnYFTpbBOja4qhbdDnDCryGiZ8ycLkBGlc7PioiSiVqCo1Py+pJrpYenA3xrguv/Z5hdNjJ3fm4dl8GDrV9kgjtNe8E388kitISpimAi5QuwvxfJS8YiRPKm9VSfs3laMlSVXjhMdlAW1PPcrcElddv+r+jMpJ9uM=

# Enable PGSQL 9.3 so that we have the 'json' type available
addons:
  postgresql: 9.3

bundler_args: "--without production development --jobs 3 --retry 3"
before_script:
  - 'sh -e /etc/init.d/xvfb start'
  - cp config/database.yml.travis config/database.yml
  - git clone --depth=1 https://github.com/rletters/solr-example.git vendor/solr
  - 'pushd vendor/solr && ./start && popd'
  - bundle exec rake db:setup

script: bundle exec rspec
