language: ruby
rvm:
  - 1.9.3
  - 2.0

branches:
  only:
    - master

bundler_args: --without production development

before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "mkdir downloads"

script:
  - "bundle exec rake spec"

matrix:
  allow_failures:
    - rvm: 2.0
