language: ruby

rvm:
  - 1.9.3
  - 2.0
  - jruby-19mode
env: JRUBY_OPTS="-Xcompile.invokedynamic=false"
gemfile:
  - gemfiles/Gemfile.mri
  - gemfiles/Gemfile.jruby

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.jruby
      env: JRUBY_OPTS="-Xcompile.invokedynamic=false"
    - rvm: 2.0
      gemfile: gemfiles/Gemfile.jruby
      env: JRUBY_OPTS="-Xcompile.invokedynamic=false"
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.mri
      env: JRUBY_OPTS="-Xcompile.invokedynamic=false"

before_install: gem install --pre bundler
bundler_args: --without production development

before_script: cp config/database.yml.travis config/database.yml
script: bundle exec rspec
