language: ruby
rvm: 2.1.1

env:
  - RAKE_TASK=spec
  - RAKE_TASK=cucumber

bundler_args: --without production development
before_script:
  - cp config/database.yml.travis config/database.yml
  - git clone --depth=1 https://github.com/rletters/solr-example.git vendor/solr
  - 'pushd vendor/solr && ./start && popd'
  - bundle exec rake db:create db:schema:load

script: 'bundle exec rake $RAKE_TASK'

after_script: 'pushd vendor/solr && ./stop && popd'
