sudo: required
dist: trusty

language: ruby
rvm: 2.4.2

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

env:
  global:
    - TMPDIR=$TRAVIS_BUILD_DIR/tmp
    - DISPLAY=":99.0"
    - DATABASE_URL="postgres:///rletters_test?username=postgres&pool=20&encoding=unicode"
    - secure: Lv1neEs259UnYFTpbBOja4qhbdDnDCryGiZ8ycLkBGlc7PioiSiVqCo1Py+pJrpYenA3xrguv/Z5hdNjJ3fm4dl8GDrV9kgjtNe8E388kitISpimAi5QuwvxfJS8YiRPKm9VSfs3laMlSVXjhMdlAW1PPcrcElddv+r+jMpJ9uM=

sudo: required
dist: trusty
addons:
  postgresql: 9.6
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl1.2-dev libsdl-ttf2.0-dev

install:
  - jdk_switcher home oraclejdk9
  - git clone --depth=1 https://github.com/rletters/solr-example.git vendor/solr
  - bundle install --without production development --jobs 3 --retry 3
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

before_script:
  - sh -e /etc/init.d/xvfb start
  - ln -s .env.example .env
  - 'pushd vendor/solr && ./start && popd'
  - bin/rails RAILS_ENV=test db:setup yarn:install

script:
  - bundle exec rails test
  - bundle exec rails test:system
  - bundle exec codeclimate-test-reporter
