language: ruby
rvm: 2.1.1

env:
  - TASK='bundle exec rspec'
  - TASK='bundle exec cucumber --profile first_try || bundle exec cucumber --profile second_try'

bundler_args: --without production development
before_script:
  - cp config/database.yml.travis config/database.yml
  - git clone --depth=1 https://github.com/rletters/solr-example.git vendor/solr
  - 'pushd vendor/solr && ./start && popd'
  - bundle exec rake db:create db:schema:load

script: $TASK

after_script: 'pushd vendor/solr && ./stop && popd'
