<%
rerun_tests = File.file?('tmp/cucumber-rerun.txt') ?
  IO.read('tmp/cucumber-rerun.txt') : ""
rerun_opts = if rerun_tests.to_s.strip.empty?
  "--tags @pass_without_doing_anything --strict"
else
  "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict -r features #{rerun_tests}"
end

first_try = '--format rerun --out tmp/cucumber-rerun.txt'
%>
default: features
wip: --tags @wip --wip features

first_try: <%= first_try %> features
second_try: <%= rerun_opts %>
