<%
rerun_tests = File.file?('tmp/cucumber-rerun.txt') ?
  IO.read('tmp/cucumber-rerun.txt') :
  ""

rerun_opts = if rerun_tests.to_s.strip.empty?
  "--tags @none_so_will_pass --strict"
else
  "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict #{rerun_tests}"
end

first_try = '--format rerun --out tmp/cucumber-rerun.txt'
%>
default: features
wip: --tags @wip --wip features

first_try: <%= first_try %> features
second_try: <%= rerun_opts %>
