common: &common
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  encoding: unicode

development:
  <<: *common
production:
  <<: *common
test:
  <<: *common
