# Leave the default translation blank
en:
  
# Spanish (Charles Pence)
es:
  documents: documentos
  terms: t%C3%A9rminos
  text: texto
  concordance: concordancia
  search: buscar
  link: enlace
  targets: destinos
  export: exportar
  formats: formatos
  about: sobre
  languages: lenguajes
  help: ayuda
  options: opci%C3%B3nes

# There must be a block for every locale, even ones that are not yet finished,
# as the redirects will fail otherwise
ar:
  
cs:
  
cy:
  
da:
  
de:
  
eo:
  
et:
  
eu:
  
fa:
  
fi:
  
fr:
  
gsw:
  
he:
  
hi:
  
is:
  
it:
  
ja:
  
ko:
  
lv:
  
nb:
  
nl:
  
pl:
  
pt:
  
ru:
  
sk:
  
sv:
  
sw:
  
th:
  
uk:
  
zh:
  
