# Leave the default translation blank
en:
  

# Spanish (Charles Pence)
es:
  documents: documentos
  terms: t%C3%A9rminos
  text: texto
  concordance: concordancia
  search: buscar
  link: enlace
  targets: destinos
  export: exportar
  formats: formatos
  about: sobre-evotext
  languages: lenguajes
  help: ayuda

